backend:
  name: github
  repo: eli1939/-1939
  branch: main
  local_backend: true

media_folder: "static/assets"
public_folder: "/assets"

collections:
  - name: "test_collection"
    label: "אוסף בדיקה"
    folder: "_posts/test"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "כותרת", name: "title", widget: "string"}
      - {label: "גוף טקסט", name: "body", widget: "markdown"}
